server {
listen 80;
server_name _;

root /usr/share/nginx/html;
index index.html;

location / {
try_files $uri $uri/ /index.html;
}

location /_framework/ {
try_files $uri =404;
}

location /service-worker.js {
add_header Cache-Control "no-cache";
try_files $uri =404;
}

location /service-worker-assets.js {
add_header Cache-Control "no-cache";
try_files $uri =404;
}
}